version: '3.8'
services:
 db:
  container_name: rest_postgres
  image: postgres:latest
  environment:
   POSTGRES_DB: biblioteca 
   POSTGRES_USER: anderson_u
   POSTGRES_PASSWORD: semedo_p
  volumes:
   - postgres_data:/var/lib/postgresql/postgres_data
  ports:
   - "5437:5432"
  restart: always
  networks:
   - rest_network

 pgadmin:
  container_name: rest_pgadmin
  image: dpage/pgadmin4
  environment:
   PGADMIN_DEFAULT_EMAIL: admin@admin.com
   PGADMIN_DEFAULT_PASSWORD: admin
  ports:
   - "8172:80"
  depends_on:
   - db
  restart: on-failure
  networks:
   - rest_network

volumes:
 postgres_data:

networks:
 rest_network:
  driver: bridge