version: '3.8'
services:
 postgresqldb:
  container_name: postgresdb
  image: postgres:latest
  ports:
   - "5432:5432"
  environment:
   POSTGRES_DB: biblioteca
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: postgres
  volumes:
   - postgres_data:/var/lib/postgresql/postgres_data

 app:
  container_name: app
  image: anderson-biblioteca:1.0.0
  build:
   context: .
   dockerfile: Dockerfile
  ports:
   - "8080:8080"
  depends_on:
   -  postgresqldb

volumes:
 postgres_data:


##networks:
 ##app_network:
  ##driver: bridge